### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by levitskyyy** [Ynfuien/YVanish#1]
# Console logs

```
[17:01:45 WARN]: [YVanish] Plugin YVanish v0.0.5 generated an exception while executing task 12
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.network.ServerGamePacketListenerImpl.send(net.minecraft.network.protocol.Packet)" because "org.bukkit.craftbukkit.entity.CraftPlayer.getHandle().connection" is null
        at org.bukkit.craftbukkit.entity.CraftPlayer.sendActionBar(CraftPlayer.java:3191) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at YVanish-0.0.5.jar/pl.ynfuien.yvanish.core.ActionAndBossBars.sendActionBar(ActionAndBossBars.java:84) ~[YVanish-0.0.5.jar:?]
        at YVanish-0.0.5.jar/pl.ynfuien.yvanish.core.ActionAndBossBars.lambda$startIntervals$0(ActionAndBossBars.java:34) ~[YVanish-0.0.5.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Ynfuien** [comment]
Check out [0.0.6](https://modrinth.com/plugin/yvanish/version/BEQeLkIQ), if the issue still occurs, let me know
