### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by levitskyyy** [Ynfuien/YVanish#2]
```
[16:41:41 WARN]: [YVanish] Plugin YVanish v0.0.6 generated an exception while executing task 23
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.network.ServerGamePacketListenerImpl.send(net.minecraft.network.protocol.Packet)" because "org.bukkit.craftbukkit.entity.CraftPlayer.getHandle().connection" is null
        at org.bukkit.craftbukkit.entity.CraftPlayer.sendActionBar(CraftPlayer.java:3191) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
        at YVanish-0.0.6.jar/pl.ynfuien.yvanish.core.ActionAndBossBars.sendActionBar(ActionAndBossBars.java:85) ~[YVanish-0.0.6.jar:?]
        at YVanish-0.0.6.jar/pl.ynfuien.yvanish.core.ActionAndBossBars.lambda$startIntervals$0(ActionAndBossBars.java:34) ~[YVanish-0.0.6.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Ynfuien** [comment]
Alright, so it still happens. Send the whole log, so I can find the cause easier.
